In [1]:
# Initial imports
import pandas as pd
import numpy as np
from pathlib import Path
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
df_2023 = pd.read_csv('../election_resources/biden_v_trump24.csv')
df_2023.fillna(0, inplace=True)
df_2023.head()

samplesize party  results  favorability
0      1500.0     d        0     -22.33400
1      1178.0     d        0     -20.66730
2      1076.0     d        0     -12.66730
3      2000.0     d        0     -14.43379
4      1500.0     d        0     -29.66750

In [3]:
# load, no need to initialize the loaded_rf
loaded_rf = joblib.load("./random_forest.joblib")

In [4]:
df_2023 = pd.get_dummies(df_2023, dtype=float)

In [6]:
y = df_2023['results'].values.reshape(-1,1)
X = df_2023.drop(['results'], axis=1).values
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [8]:
scaler = StandardScaler()

In [9]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X)

In [10]:
# Scale the training data
X_scaled = X_scaler.transform(X)


In [11]:
# Making predictions using the testing data
predictions2 = loaded_rf.predict(X_scaled)
predictions2

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [12]:
display(y)
display(predictions2)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
display(predictions2.shape)
display(y.shape)

(1662,)

(1662, 1)

In [14]:
# Calculating the confusion matrix
cm = confusion_matrix(y, predictions2)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y, predictions2)

ValueError: Shape of passed values is (1, 1), indices imply (2, 2)