In [1]:
# Initial imports
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
df_2019 = pd.read_csv('../election_resources/cleaned_2019_data.csv')
df_2019.fillna(0, inplace=True)
df_2019.head()

question_id    end_date pollster  sample_size population  \
0       114577  2019-12-10   YouGov         1195         rv   
1       114585  2019-12-10   YouGov         1198         rv   
2       114589  2019-12-10   YouGov         1198         rv   
3       114593  2019-12-10   YouGov         1198         rv   
4       114597  2019-12-10   YouGov         1202         rv   

          politician  favorable  unfavorable  very_favorable  \
0  Michael F. Bennet       14.0         29.0             4.0   
1  Michael Bloomberg       24.0         58.0             7.0   
2     Cory A. Booker       35.0         45.0            11.0   
3      Steve Bullock       14.0         27.0             3.0   
4     Pete Buttigieg       35.0         44.0            14.0   

   somewhat_favorable  somewhat_unfavorable  very_unfavorable  results  
0                10.0                  12.0              17.0        0  
1                17.0                  20.0              38.0        0  
2                24.0                  12.0              33.0        0  
3                11.0                  11.0              16.0        0  
4                21.0                  13.0              31.0        0

In [3]:
X = df_2019.copy()
X = X.drop(columns=['question_id', 'end_date'])
X.head()

pollster  sample_size population         politician  favorable  unfavorable  \
0   YouGov         1195         rv  Michael F. Bennet       14.0         29.0   
1   YouGov         1198         rv  Michael Bloomberg       24.0         58.0   
2   YouGov         1198         rv     Cory A. Booker       35.0         45.0   
3   YouGov         1198         rv      Steve Bullock       14.0         27.0   
4   YouGov         1202         rv     Pete Buttigieg       35.0         44.0   

   very_favorable  somewhat_favorable  somewhat_unfavorable  very_unfavorable  \
0             4.0                10.0                  12.0              17.0   
1             7.0                17.0                  20.0              38.0   
2            11.0                24.0                  12.0              33.0   
3             3.0                11.0                  11.0              16.0   
4            14.0                21.0                  13.0              31.0   

   results  
0        0  
1        0  
2        0  
3        0  
4        0

In [4]:
df_2019 = pd.get_dummies(df_2019, dtype=float)

In [5]:
y = df_2019['results'].values.reshape(-1,1)
X = df_2019.drop(['results'], axis=1).values
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [6]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [7]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [8]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X_train)

In [9]:
# Scale the training data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
# Create the random forest classifier instance
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

In [11]:
# Fit the model and use .ravel()on the "y_train" data. 
rf_model = rf_model.fit(X_train_scaled, y_train.ravel())

In [12]:
# Making predictions using the testing data
predictions = rf_model.predict(X_test_scaled)

In [13]:
display(predictions.shape)
display(y.shape)

(408,)

(1631, 1)

In [14]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [15]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          356            0
Actual 1            0           52

Accuracy Score : 1.0
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       356
           1       1.00      1.00      1.00        52

    accuracy                           1.00       408
   macro avg       1.00      1.00      1.00       408
weighted avg       1.00      1.00      1.00       408



In [16]:
df_2023 = pd.read_csv('../election_resources/cleaned_2023_data.csv')
df_2023.drop(columns=['question_id', 'end_date'])
df_2023.fillna(0, inplace=True)
df_2023.head()

question_id    end_date pollster  sample_size population    politician  \
0       178640  2023-08-08   YouGov       1500.0          a  Donald Trump   
1       178641  2023-08-08   YouGov       1178.0         rv  Donald Trump   
2       178646  2023-08-08   YouGov       1500.0          a     Joe Biden   
3       178647  2023-08-08   YouGov       1178.0         rv     Joe Biden   
4       178652  2023-08-08   YouGov       1500.0          a    Mike Pence   

   favorable  unfavorable  very_favorable  somewhat_favorable  \
0       41.0         56.0            21.0                20.0   
1       41.0         58.0            23.0                18.0   
2       44.0         53.0            20.0                24.0   
3       45.0         53.0            23.0                22.0   
4       27.0         58.0             6.0                21.0   

   somewhat_unfavorable  very_unfavorable  results  
0                  12.0              44.0        0  
1                  11.0              47.0        0  
2                  13.0              40.0        0  
3                  11.0              42.0        0  
4                  27.0              31.0        0

In [17]:
df_2023 = pd.get_dummies(df_2023, dtype=float)

In [18]:
yy = df_2023['results'].values.reshape(-1,1)
Xx = df_2023.drop(['results'], axis=1).values
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [19]:
# Splitting into Train and Test sets
Xx_train, Xx_test, yy_train, yy_test = train_test_split(Xx, yy, random_state=78)

In [20]:
scaler = StandardScaler()

In [21]:
# Fit the Standard Scaler with the training data
Xx_scaler = scaler.fit(Xx_train)

In [22]:
# Scale the training data
Xx_train_scaled = Xx_scaler.transform(Xx_train)
Xx_test_scaled = Xx_scaler.transform(Xx_test)

In [23]:
# Create the random forest classifier instance
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

In [24]:
# Fit the model and use .ravel()on the "y_train" data. 
rf_model = rf_model.fit(Xx_train_scaled, yy_train.ravel())

In [25]:
# Making predictions using the testing data
predictions2 = rf_model.predict(Xx_test_scaled)
predictions2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [26]:
display(yy_test)
display(predictions2)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [28]:
# Calculating the confusion matrix
cm = confusion_matrix(yy_test, predictions2)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(yy_test, predictions2)

ValueError: Shape of passed values is (1, 1), indices imply (2, 2)