In [5]:
# Initial imports
import pandas as pd
import numpy as np
from pathlib import Path
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [6]:
df_2023 = pd.read_csv('../election_resources/biden_v_trump24.csv')
df_2023.fillna(0, inplace=True)
df_2023.head()

end_date  samplesize  results  favorability_r  favorability_d
0  2023-08-08      1500.0        0        -30.3341        -22.3340
1  2023-08-08      1500.0        0        -30.3341        -20.6673
2  2023-08-08      1178.0        0        -33.0008        -22.3340
3  2023-08-08      1178.0        0        -33.0008        -20.6673
4  2023-08-03      1076.0        0        -19.3343        -12.6673

In [7]:
df_2023 = df_2023.drop(columns=['end_date'])
df_2023.head()

samplesize  results  favorability_r  favorability_d
0      1500.0        0        -30.3341        -22.3340
1      1500.0        0        -30.3341        -20.6673
2      1178.0        0        -33.0008        -22.3340
3      1178.0        0        -33.0008        -20.6673
4      1076.0        0        -19.3343        -12.6673

In [8]:
# load, no need to initialize the loaded_rf
loaded_rf = joblib.load("./random_forest.joblib")

In [9]:
df_2023 = pd.get_dummies(df_2023, dtype=float)
df_2023.head()

samplesize  results  favorability_r  favorability_d
0      1500.0        0        -30.3341        -22.3340
1      1500.0        0        -30.3341        -20.6673
2      1178.0        0        -33.0008        -22.3340
3      1178.0        0        -33.0008        -20.6673
4      1076.0        0        -19.3343        -12.6673

In [10]:
y = df_2023['results'].values.reshape(-1,1)
X = df_2023.drop(['results'], axis=1).values
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [11]:
scaler = StandardScaler()

In [12]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X)

In [13]:
# Scale the training data
X_scaled = X_scaler.transform(X)


In [14]:
# Making predictions using the testing data
predictions2 = loaded_rf.predict(X_scaled)
predictions2

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [15]:
display(y)
display(predictions2)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [11]:
y2 = y.astype(float)
predictions22 = predictions2.astype(float)

In [12]:
display(y2.dtype)
display(predictions22.dtype) 

dtype('float64')

dtype('float64')

In [17]:
display(predictions2.shape)
display(y.shape)

(1799,)

(1799, 1)

In [19]:
# Calculating the confusion matrix
cm = confusion_matrix(y, predictions2)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y, predictions2)

In [22]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y, predictions2))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0            3         1796
Actual 1            0            0

Accuracy Score : 0.0016675931072818232
Classification Report
              precision    recall  f1-score   support

           0       1.00      0.00      0.00      1799
           1       0.00      0.00      0.00         0

    accuracy                           0.00      1799
   macro avg       0.50      0.00      0.00      1799
weighted avg       1.00      0.00      0.00      1799



c:\Users\micha\anaconda3\envs\ml_main\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\micha\anaconda3\envs\ml_main\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\micha\anaconda3\envs\ml_main\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [23]:
avg = predictions2.mean()
avg

0.9983324068927182