In [1]:
# Initial imports
import pandas as pd
import numpy as np
from pathlib import Path
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
df_2023 = pd.read_csv('../election_resources/biden_v_trump24.csv')
df_2023.fillna(0, inplace=True)
df_2023.head()

samplesize party  results  favorability
0      1500.0     d        0     -22.33400
1      1178.0     d        0     -20.66730
2      1076.0     d        0     -12.66730
3      2000.0     d        0     -14.43379
4      1500.0     d        0     -29.66750

In [3]:
# load, no need to initialize the loaded_rf
loaded_rf = joblib.load("./random_forest.joblib")

In [4]:
df_2023 = pd.get_dummies(df_2023, dtype=float)
df_2023.head()

samplesize  results  favorability  party_d  party_r
0      1500.0        0     -22.33400      1.0      0.0
1      1178.0        0     -20.66730      1.0      0.0
2      1076.0        0     -12.66730      1.0      0.0
3      2000.0        0     -14.43379      1.0      0.0
4      1500.0        0     -29.66750      1.0      0.0

In [5]:
y = df_2023['results'].values.reshape(-1,1)
X = df_2023.drop(['results'], axis=1).values
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [6]:
scaler = StandardScaler()

In [7]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X)

In [8]:
# Scale the training data
X_scaled = X_scaler.transform(X)


In [9]:
# Making predictions using the testing data
predictions2 = loaded_rf.predict(X_scaled)
predictions2

array([0., 0., 0., ..., 1., 1., 1.])

In [10]:
display(y)
display(predictions2)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

array([0., 0., 0., ..., 1., 1., 1.])

In [11]:
y2 = y.astype(float)
predictions22 = predictions2.astype(float)

In [12]:
display(y2.dtype)
display(predictions22.dtype) 

dtype('float64')

dtype('float64')

In [13]:
display(predictions22.shape)
display(y2.shape)

(1662,)

(1662, 1)

In [14]:
# Calculating the confusion matrix
cm = confusion_matrix(y2, predictions22)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y2, predictions22)

In [16]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y2, predictions22))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          810          852
Actual 1            0            0

Accuracy Score : 0.48736462093862815
Classification Report
              precision    recall  f1-score   support

         0.0       1.00      0.49      0.66      1662
         1.0       0.00      0.00      0.00         0

    accuracy                           0.49      1662
   macro avg       0.50      0.24      0.33      1662
weighted avg       1.00      0.49      0.66      1662



c:\Users\micha\anaconda3\envs\ml_main\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\micha\anaconda3\envs\ml_main\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\micha\anaconda3\envs\ml_main\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
